---
title: "Compare work-focus codings in `res1B`"
subtitle: "Seeing the world differently"
author: "Michael Garrett"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{"Compare-within-res1B"}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)  # map, mutate, filter, gather, select, group_by, summarize
library(wkFocus)
```

## Compare

```{r res1B}
# List coders
coders <- res1B_focus %>% 
  map("name") %>% 
  map(wkf_parse_dspath) %>% 
  map("coder")
coders

ts <- res1B_focus[1:2] %>% 
  map(~ wkf_tsample(ds = ., dt = 1, warn = FALSE))

tsAB <- as.data.frame(list(A = ts[[1]]$data, B = ts[[2]]$data))

agreeAB <- tsAB %>%
  transpose() %>%
  map_df(~ compAB_at_time(tsAB = .))

agreeAB <- agreeAB %>%
  mutate(t = tsAB$A.t) %>%
  gather(key = n, value = d, d1:d2) %>%
  filter(d != "N") %>%
  select(-n)

agreeAB <- list(names = ts %>% map("name"), data = agreeAB)

agreeAB$data %>% group_by(d) %>% summarize(n = n())

save(agreeAB,
  file = file.path("out", paste0("agreeAB", "_20180110", "_02", ".rda")))
```

```{r plot}
cap <- paste0("Vertical bands show disagreements between coding datasets: \n", 
             "[1] ", agreeAB$names[[1]],  "\n [2] ", agreeAB$names[[2]], "\n",
             "Horizontal bands show codestamps for the dataset [1]")
title <- "Plot of coding disagreements for phase res1B"

wkf_pl_comps(agreeAB$data, which = "D",
          cst_df = res1B_focus[[1]]$data,
          pl_labs = list(caption = cap, title = title))
```

