---
pagetitle: "Comparing two codings of work focus"
subtitle: "Seeing the world differently"
author: "Michael Garrett"
date: "`r Sys.Date()`"
params:
   dataset: res1B
   codingA: 2
   codingB: 3
   timestep: 60
output: 
  rmarkdown::html_document:
    css: ../css/simple_report.css
vignette: >
  %\VignetteIndexEntry{"Compare-two-codings"}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
knitr::opts_chunk$set(fig.width = 7, fig.height = 5)

library(tidyverse)  # map, mutate, filter, gather, select, group_by, summarize
library(knitr)
library(wkFocus)

## Set local vignette parameters

ds_list_name <- paste0(params$dataset, "_focus")

```

# "Compare '`r ds_list_name`' codings"

## Get data

```{r load_dat}

## Read dataset from package data into "Global" environment

load(file.path("..", "data", paste0(ds_list_name, ".rda")))

#  Flip parameter to a "Global" symbol to be used throughout vignette

ds_list <-  eval(as.symbol(ds_list_name))

```


```{r inspect_dat}

nsets <- length(ds_list)

sessions <- ds_list %>% map_chr(c("ds_id", "sid"))
coders   <- ds_list %>% map_chr(c("ds_id", "coder"))
versions <- ds_list %>% map_chr(c("ds_id", "version"))

## For display, get sids and data dimensions into a df 

tmp <- ds_list %>% map_df("ds_id")
ds_list %>% 
  map_df( ~ list(obs = nrow(.x$data), vars = ncol(.x$data))) %>% 
  bind_cols(tmp, .) %>% 
  kable(caption = paste("Datasets in", ds_list_name))

rm(tmp)

```

## Compare two codings

```{r comp_1_2}

## pick datasets to sample

to_comp     <- c(A = params$codingA, B = params$codingB)
time_step   <- params$timestep  # sec
```

<P style="page-break-before: always">

### Sessions: `r sessions[to_comp]`; Coders: `r coders[to_comp]`; Versions: `r versions[to_comp]`.

```{r decide_agr}

## timesample each dataset
ts_list <- wkf_tsample(ds_list[to_comp], dt = time_step)

## compare coding decsions 
agrAB <- wkf_compAB(ts_list)

## summarize results
agrAB$data %>% group_by(d) %>% summarize(n = n()) %>% 
  kable(caption = paste("Summary of Agreements between codings"),
        col.names = c("Decision", "Count")
  )

```


```{r plot}

cap   <- paste0("Vertical bands show disagreements between coding datasets: ", 
            agrAB$ds_id$A$version, " & ", agrAB$ds_id$B$version)
title <- paste0("Plot of coding disagreements for phase ", ds_list_name)

wkf_pl_comps(agrAB, to_plot = "D",
          ds_stack = wkf_stack_cstamps(ds_list),
          pl_labs = list(caption = cap, title = title)) + 
  theme_bw() +
  facet_wrap(~coder, ncol = 1)

```

