---
title: "compare-res1A"
author: "Michael Garrett"
date: "1/10/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)  # map, mutate, filter, gather, select, group_by, summarize
library(wkFocus)
```

## Compare

```{r res1A}
# List coders
coders <- res1A_focus_hand_cstamp %>% 
  map("name") %>% 
  map(wkf_parse_dspath) %>% 
  map("coder")
coders

ts <- res1A_focus_hand_cstamp[1:2] %>% 
  map(~ wkf_tsample_cstamps(ds = ., dt = 60, warn = FALSE))

tsAB <- as.data.frame(list(A = ts[[1]]$data, B = ts[[2]]$data))

agreeAB <- tsAB %>%
  transpose() %>%
  map_df(~ wkf_compAB_tsample(tsAB = .))

agreeAB <- agreeAB %>%
  mutate(t = tsAB$A.t) %>%
  gather(key = n, value = d, d1:d2) %>%
  filter(d != "N") %>%
  select(-n)

agreeAB <- list(names = ts %>% map("name"), data = agreeAB)

agreeAB$data %>% group_by(d) %>% summarize(n = n())

save(agreeAB,
  file = file.path("out", paste0("agreeAB", "_20180110", "_02", ".rda")))
```

```{r plot}
cap <- paste0("Vertical bands show disagreements between coding datasets: \n", 
             "[1] ", agreeAB$names[[1]],  "\n [2] ", agreeAB$names[[2]], "\n",
             "Horizontal bands show codestamps for the dataset [1]")
title <- "Plot of coding disagreements for phase res1A"

wkf_pl_compAB(agreeAB$data, which = "D",
          cst_df = res1A_focus_hand_cstamp[[1]]$data,
          pl_labs = list(caption = cap, title = title))
```

