---
title: "Dataset 'res2C_focus': Initial exploration"
subtitle: "Seeing the world differently"
author: "Michael Garrett"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document
vignette: >
  %\VignetteIndexEntry{"Explore-res2C"}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r setup, message = FALSE, warning = FALSE, echo = FALSE}

# Packages -------------------------

# Dataset manipulation
library(tidyverse)

# Formating output
library(knitr)
library(kableExtra)
library(pander)

# Chunk options
opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)  
opts_chunk$set(comment = NA)  # do not prepend chunk results with a marker
opts_chunk$set(fig.path = "images/")  # dump a copy of the figures here

## Get global parameters

pars <- wkFocus::wkf_config()

## Set local vignette parameters

ds_list_name <- "res2C_focus"

```


```{r load_dat}

## Read dataset from package data into "Global" environment

load(file.path("..", "data", paste0(ds_list_name, ".rda")))

# Flip parameter to a "Global" symbol to be used as a handle on the dataset
#  throughout vignette. Eg, if ds_list_name is "res1A_focus", `ds_list` will
#  point to a copy of the loaded dataset with that name.

ds_list <-  eval(as.symbol(ds_list_name))

```

### Specifications for coding sets in this dataset

```{r inspect_dat, results="asis"}

ds_specs <- ds_list %>% {
  tibble(
    codeset  = seq_along(ds_list),
    sid      = map_chr(., c("ds_id", "sid")),
    coder    = map_chr(., c("ds_id", "coder")),
    version  = map_chr(., c("ds_id", "version")),
    source   = map_chr(., "ds_src"), 
    type     = map_chr(., "ds_type"),
    cstamps  = map_int(., ~ nrow(.x$data)),
    duration = map(., ~ max(.x$data$Out) - min(.x$data$In))
  )
}

ds_specs %>% 
  kable(align = "l", caption = paste("Specifications for datasets in", ds_list_name)) %>%
  kable_styling(position = "left") 

```

### Initial records for this dataset

```{r sample_dat, results="asis"}

# Print first few records of each dataset
ds_list %>% {
  # create a list with IDs and sample data
  list(
    id = map(., ~ paste(.$ds_id, collapse = "-")),
    data = map(., ~ head(.$data, 3)))
} %>% 
  # turn it around to pair ids with df of data records
  transpose() %>% 
  # send each pair to the kable function
  map(~ kable(.x$data, caption = .x$id))
  
```

### Summarize coding variables in each code set

```{r summarize_dat}

## Here I'm creating various display tables by using purrr::map and dplyr::*
#  NB. the processing by map_dfr accumulates the results for each codeset
#  and tags them with an index

# Present count of NAs in each variable
ds_list %>% 
  map_dfr(~ summarize(.$data, 
              cstamps = n(), 
              NArounds = sum(is.na(round)), 
              NAgid = sum(is.na(gid)), 
              NAtypes = sum(is.na(type)), 
              NAbins = sum(is.na(bin)), 
              NAIns = sum(is.na(In)), 
              NAOuts = sum(is.na(Out)), 
              NAcodes = sum(is.na(code))), 
          .id = "codeset") %>% 
  kable(caption = paste("Missing values (NA) in ", ds_list_name)) %>%
  kable_styling(position = "left")

# Present counts of codes by round, group, type, and facilitation status (bin)
#  As a data check, each codeset should have single roundxgidxtype.
ds_list %>% 
  map( ~ group_by(.x$data, round, gid, type, bin)) %>% 
  map_dfr( ~ summarize(.x, n = n()), 
           .id = "codeset") %>% 
  kable(caption = paste("Summary of facilitation bins in", ds_list_name)) %>%
  kable_styling(position = "left")
 
# Present counts of each of the types of focus codes.
ds_list %>% 
  # complete adds one entry for any codes not represented, filled w/ NAs
  map( ~ complete(.x$data, code)) %>% 
  map( ~ group_by(.x, code)) %>% 
  map_dfr( ~ summarize(.x, n = sum(!is.na(bin))),
           .id = "codeset") %>% 
  spread(code, n, drop = FALSE) %>% 
  mutate(total = Rd + Do + Rp + Ds + O + Of) %>% 
  kable(caption = paste("Counts of codes in", ds_list_name)) %>% 
  kable_styling(position = "left")

# Summary stats of codestamp duration by facilitation type
ds_list %>% 
  map( ~ mutate(.x$data, duration = Out - In)) %>% 
  map( ~ group_by(.x, bin, add = TRUE)) %>% 
  map_dfr( ~ summarize(.x, n = sum(!is.na(In)), 
                       total = sum(duration, na.rm = TRUE),
                       mean = mean(duration, na.rm = TRUE),
                       sd   = sd(duration, na.rm = TRUE),
                       q0 = min(duration),
                       q1 = quantile(duration, probs = .25, na.rm = TRUE),
                       q2 = quantile(duration, probs = .50, na.rm = TRUE),
                       q3 = quantile(duration, probs = .75, na.rm = TRUE),
                       q4 = max(duration)
  ),
  .id = "codeset"
  ) %>% 
  kable(caption = paste("Summary statistics of codestamp lengths by facilitation typ in", ds_list_name),
        digits = 1) %>% 
  kable_styling(position = "left")

# Summary stats  of codestamp duration by focus code
ds_list %>% 
  map( ~ complete(.x$data, bin, code)) %>%
  map( ~ mutate(.x, duration = Out - In)) %>% 
  map( ~ group_by(.x, code, add = TRUE)) %>% 
  map_dfr( ~ summarize(.x, n = sum(!is.na(In)), 
                       total = sum(duration, na.rm = TRUE),
                       mean = mean(duration, na.rm = TRUE),
                       sd   = sd(duration, na.rm = TRUE),
                       q0 = min(duration),
                       q1 = quantile(duration, probs = .25, na.rm = TRUE),
                       q2 = quantile(duration, probs = .50, na.rm = TRUE),
                       q3 = quantile(duration, probs = .75, na.rm = TRUE),
                       q4 = max(duration)
  ),
  .id = "codeset"
  ) %>% 
  kable(caption = paste("Summary statistics of codestamp lengths by focus code in", ds_list_name),
        digits = 1) %>% 
  kable_styling(position = "left")

# Summary stats of codestamp duration by bin X focus code
ds_list %>% 
  map( ~ complete(.x$data, bin, code)) %>%
  map( ~ mutate(.x, duration = Out - In)) %>% 
  map( ~ group_by(.x, bin, code, add = TRUE)) %>% 
  map_dfr( ~ summarize(.x, n = sum(!is.na(In)), 
                   total = sum(duration, na.rm = TRUE),
                   mean = mean(duration, na.rm = TRUE),
                   sd   = sd(duration, na.rm = TRUE),
                   q0 = min(duration),
                   q1 = quantile(duration, probs = .25, na.rm = TRUE),
                   q2 = quantile(duration, probs = .50, na.rm = TRUE),
                   q3 = quantile(duration, probs = .75, na.rm = TRUE),
                   q4 = max(duration)
                   ),
           .id = "codeset"
       ) %>% 
  kable(caption = paste("Summary statistics of codestamp lengths in", ds_list_name),
        digits = 1) %>% 
  kable_styling(position = "left")



```

