---
title: "Study of coder reliability"
subtitle: "_Seeing the world differently_ dissertaton"
author: "Michael Garrett"
institute: East Tennessee State University
thanks: Draft version 20171125
date: "`r format(Sys.time(), '25 November, 2017')`"

fontsize: 11pt

output:
  tufte::tufte_handout:
    df_print: kable
    fig_caption: yes
    fig_height: 4
    includes:
      in_header:
      - ~/Documents/sup/latex/includes/use_sansmath.tex
      - ~/Documents/sup/latex/includes/diss_std.tex
    keep_tex: no
  tufte::tufte_book:
    citation_package: natbib
  tufte::tufte_html: default
---

```{r setup, message = FALSE, warning = FALSE, echo = FALSE}

## Environment assumes these packages have been installed --------------

# Dataset manipulation
library(tidyverse)
library(lubridate)  # not being installed by tidyverse

# Formating output
library(tufte)      # newthought, marginfigure
library(knitr)      # for kable()
library(kableExtra)
library(xtable)     # making latex code for margin tables
library(pander)

## External source files ----------------

source("utils/base-utils.R")  # read... functions
source("utils/plot-utils.R")  # segment plots 

## Knitr options

opts_chunk$set(comment = NA)  # do not prepend results with a marker
opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)  # do not display R in doc
opts_chunk$set(fig.path = "images/")  # dump a copy of the figures here

# From tufte .Rmd example file. Not sure of purpose
# opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
#   options(htmltools.dir.version = FALSE)

```

```{r params, message = FALSE, warning = FALSE, echo = FALSE}

# Project-wide parameter list
pars <- read_config()

# Local

#  Dataset specifiers
#  handcode-cstamp-res-1-C-focus-V20171228

dsname <- list()
dsname$fname   <- ""
dsname$Method  <- "handcode"
dsname$Stamp   <- "cstamp"
dsname$Phase   <- "res"
dsname$round   <- "1"  # ds with coding for all rounds combined
dsname$gid     <- "C"  # ds with coding for all groups
dsname$type    <- "focus"  # only focus codes
dsname$Version <- "V20171228"

dsname <- build_dsname(dsname)

# From storage, get definitions of the various codings
fc_tbl <- as_data_frame(
  readRDS(file.path(pars$data_folder, "study", "focus-code-tbl.rds")))

```

**Problem statement**

>   **1**. Time sample a set of codestamps
>
>   **2**. Compare codings at each timestep
>
>   **3**. Computer simple percent agreement between the coders
>
>   **4**. Visualize the disagreements and correlate with codings
>
>    Code dataset:
>
>   `r dsname$fname`

# Introduction


